run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - dupl
    - path: internal/quotes/quotes\.go
      linters:
        - lll  # Long lines are acceptable for quote strings
  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at' 