name: Bug Report
description: File a bug report to help us improve zenta
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. See error '...'
        3. Expected '...' but got '...'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you running zenta in?
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Terminal: [e.g. iTerm2, gnome-terminal, Windows Terminal]
        - Shell: [e.g. zsh, bash, fish]
        - zenta version: [e.g. 0.1.0] (run `zenta version`)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Screenshots, error messages, logs, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 